// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Data;

#nullable disable

namespace Zoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20240628184300_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CategorySpecies");
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Reinhold",
                            Personality = "Maxwell",
                            PreferredDiet = "[]",
                            SpeciesId = 12,
                            Weight = 583.99384218992839,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Clementine",
                            Personality = "Nicolette",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 922.09735241551175,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            EnclosureId = 4,
                            Gender = 1,
                            Name = "Justyn",
                            Personality = "Orland",
                            PreferredDiet = "[]",
                            SpeciesId = 19,
                            Weight = 73.678940402020686,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnclosureId = 11,
                            Gender = 1,
                            Name = "Oleta",
                            Personality = "Florencio",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 292.70083879459168,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Dulce",
                            Personality = "Gregorio",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 28.621354260867204,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            EnclosureId = 23,
                            Gender = 0,
                            Name = "Adrienne",
                            Personality = "Marlee",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 310.26664344476649,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 7,
                            EnclosureId = 4,
                            Gender = 1,
                            Name = "Arianna",
                            Personality = "Rogelio",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 363.34351295072241,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Carter",
                            Personality = "Maymie",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 339.79810353751037,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            EnclosureId = 14,
                            Gender = 0,
                            Name = "Jo",
                            Personality = "Lilliana",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 883.57638563642149,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 10,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Erik",
                            Personality = "Donald",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 780.69339139383749,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 11,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Milan",
                            Personality = "Javier",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 912.71971748270596,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Charlie",
                            Personality = "Cassandra",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 429.5497026290779,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            EnclosureId = 16,
                            Gender = 0,
                            Name = "Rowena",
                            Personality = "Romaine",
                            PreferredDiet = "[]",
                            SpeciesId = 24,
                            Weight = 937.53173299641446,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Isidro",
                            Personality = "Brycen",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 20.410098982445295,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 15,
                            EnclosureId = 21,
                            Gender = 0,
                            Name = "Shannon",
                            Personality = "Jeff",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 751.03006885634807,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            EnclosureId = 8,
                            Gender = 0,
                            Name = "Mireille",
                            Personality = "Noe",
                            PreferredDiet = "[]",
                            SpeciesId = 19,
                            Weight = 409.34013035629908,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Ettie",
                            Personality = "Esta",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 174.47088892910202,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 18,
                            EnclosureId = 8,
                            Gender = 1,
                            Name = "Meggie",
                            Personality = "Jorge",
                            PreferredDiet = "[]",
                            SpeciesId = 1,
                            Weight = 701.14730300142276,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Guy",
                            Personality = "Marjorie",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 105.38729777348733,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            EnclosureId = 18,
                            Gender = 0,
                            Name = "Leanna",
                            Personality = "Francis",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 942.52034980879591,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 21,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Dandre",
                            Personality = "Raina",
                            PreferredDiet = "[]",
                            SpeciesId = 19,
                            Weight = 75.47178610774121,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Demarcus",
                            Personality = "Lon",
                            PreferredDiet = "[]",
                            SpeciesId = 19,
                            Weight = 546.71001551133418,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            EnclosureId = 24,
                            Gender = 1,
                            Name = "Ronny",
                            Personality = "Dino",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 768.11496412915847,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 24,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Caroline",
                            Personality = "Pierce",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 4.4597895388517461,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 25,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Rosella",
                            Personality = "Emmanuelle",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 112.62275484553986,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 26,
                            EnclosureId = 22,
                            Gender = 1,
                            Name = "Maudie",
                            Personality = "Finn",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 241.75767024040732,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 27,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Felix",
                            Personality = "Tressie",
                            PreferredDiet = "[]",
                            SpeciesId = 24,
                            Weight = 77.115780611041686,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 28,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Sasha",
                            Personality = "Trudie",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 306.50247653557494,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 29,
                            EnclosureId = 11,
                            Gender = 1,
                            Name = "Katelyn",
                            Personality = "Liliana",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 469.9367846910157,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 30,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Sienna",
                            Personality = "Howard",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 158.56233311099234,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 31,
                            EnclosureId = 20,
                            Gender = 0,
                            Name = "Dashawn",
                            Personality = "Tess",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 240.05281003650663,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 32,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Louie",
                            Personality = "Stephon",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 987.69278408091486,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 33,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Serenity",
                            Personality = "Nannie",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 603.97625224516582,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 34,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Reginald",
                            Personality = "Newton",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 279.2802088715427,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 35,
                            EnclosureId = 15,
                            Gender = 0,
                            Name = "Earnest",
                            Personality = "Hallie",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 511.20347569858347,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 36,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Lora",
                            Personality = "Matilda",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 832.75294879800333,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 37,
                            EnclosureId = 3,
                            Gender = 1,
                            Name = "Madge",
                            Personality = "Blanca",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 837.72692348051692,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 38,
                            EnclosureId = 20,
                            Gender = 1,
                            Name = "Alexanne",
                            Personality = "Hailey",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 972.95455010553621,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 39,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Shanel",
                            Personality = "Kaela",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 926.76055502564009,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 40,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Reyna",
                            Personality = "Chadrick",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 467.24196335672912,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 41,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Eino",
                            Personality = "Eleanora",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 465.87783943131524,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 42,
                            EnclosureId = 8,
                            Gender = 1,
                            Name = "Werner",
                            Personality = "Albina",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 524.16402258821302,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 43,
                            EnclosureId = 24,
                            Gender = 0,
                            Name = "Richard",
                            Personality = "Stefan",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 520.86270872041496,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 44,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Alfreda",
                            Personality = "Fermin",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 329.80239024538031,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 45,
                            EnclosureId = 10,
                            Gender = 0,
                            Name = "Ada",
                            Personality = "Aric",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 948.25042902466828,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 46,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Gilberto",
                            Personality = "Deon",
                            PreferredDiet = "[]",
                            SpeciesId = 17,
                            Weight = 292.43020764660406,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 47,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Sienna",
                            Personality = "Raquel",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 55.391065840388841,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 48,
                            EnclosureId = 22,
                            Gender = 1,
                            Name = "Deontae",
                            Personality = "Eino",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 660.50993937936778,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 49,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Celine",
                            Personality = "Lilian",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 608.11200530091321,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 50,
                            EnclosureId = 3,
                            Gender = 1,
                            Name = "Mortimer",
                            Personality = "Ella",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 924.36632312009817,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 51,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Clifton",
                            Personality = "Art",
                            PreferredDiet = "[]",
                            SpeciesId = 17,
                            Weight = 514.31180701421749,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 52,
                            EnclosureId = 25,
                            Gender = 0,
                            Name = "Mustafa",
                            Personality = "Erin",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 65.811877011700844,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 53,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Wyman",
                            Personality = "Christiana",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 192.44330662876422,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 54,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Kellen",
                            Personality = "Efren",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 553.69651476068952,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 55,
                            EnclosureId = 24,
                            Gender = 1,
                            Name = "Jakob",
                            Personality = "Nicola",
                            PreferredDiet = "[]",
                            SpeciesId = 19,
                            Weight = 227.43019061863316,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 56,
                            EnclosureId = 14,
                            Gender = 0,
                            Name = "Maud",
                            Personality = "Laurence",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 489.68204851778478,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 57,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Pattie",
                            Personality = "Shane",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 744.21227502684644,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 58,
                            EnclosureId = 23,
                            Gender = 1,
                            Name = "Wilford",
                            Personality = "Kayla",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 210.12001566779617,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 59,
                            EnclosureId = 21,
                            Gender = 0,
                            Name = "Stan",
                            Personality = "Boyd",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 326.71578594588323,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 60,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Catharine",
                            Personality = "Judge",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 564.81709783411941,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 61,
                            EnclosureId = 8,
                            Gender = 0,
                            Name = "Maxime",
                            Personality = "Terry",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 473.66420935817916,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 62,
                            EnclosureId = 20,
                            Gender = 1,
                            Name = "Shanna",
                            Personality = "Lillie",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 258.75880571188929,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 63,
                            EnclosureId = 13,
                            Gender = 1,
                            Name = "Maye",
                            Personality = "Sidney",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 233.65061681283504,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 64,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Rebecca",
                            Personality = "Jack",
                            PreferredDiet = "[]",
                            SpeciesId = 21,
                            Weight = 465.81381939727464,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 65,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Dahlia",
                            Personality = "Mitchell",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 315.99335931315642,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 66,
                            EnclosureId = 22,
                            Gender = 1,
                            Name = "Marlon",
                            Personality = "Devin",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 212.32486820544179,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 67,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Jettie",
                            Personality = "Wilbert",
                            PreferredDiet = "[]",
                            SpeciesId = 12,
                            Weight = 243.6958231207114,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 68,
                            EnclosureId = 20,
                            Gender = 1,
                            Name = "Agustin",
                            Personality = "Kiel",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 652.40047605135453,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 69,
                            EnclosureId = 13,
                            Gender = 0,
                            Name = "Jefferey",
                            Personality = "Sincere",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 425.99206340312986,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 70,
                            EnclosureId = 24,
                            Gender = 1,
                            Name = "Jules",
                            Personality = "Kenyatta",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 867.14126551641198,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 71,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Carli",
                            Personality = "Bud",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 587.71482324443105,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 72,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Isabell",
                            Personality = "Kaela",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 60.882503368474246,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 73,
                            EnclosureId = 20,
                            Gender = 1,
                            Name = "Florencio",
                            Personality = "Valentin",
                            PreferredDiet = "[]",
                            SpeciesId = 1,
                            Weight = 218.25267924283597,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 74,
                            EnclosureId = 23,
                            Gender = 0,
                            Name = "Gabe",
                            Personality = "Kyla",
                            PreferredDiet = "[]",
                            SpeciesId = 1,
                            Weight = 981.05557988929456,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 75,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Magali",
                            Personality = "Dorian",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 432.01772928758277,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 76,
                            EnclosureId = 24,
                            Gender = 1,
                            Name = "Georgette",
                            Personality = "Quentin",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 469.38552882139214,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 77,
                            EnclosureId = 13,
                            Gender = 1,
                            Name = "Evelyn",
                            Personality = "Mylene",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 650.08852301729075,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 78,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Nayeli",
                            Personality = "Gavin",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 644.24274255594094,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 79,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Nathan",
                            Personality = "Gayle",
                            PreferredDiet = "[]",
                            SpeciesId = 24,
                            Weight = 190.80559048992919,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 80,
                            EnclosureId = 24,
                            Gender = 0,
                            Name = "Montana",
                            Personality = "Waino",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 838.6730568098111,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 81,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Delphia",
                            Personality = "Justus",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 509.18328678003121,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 82,
                            EnclosureId = 25,
                            Gender = 0,
                            Name = "Rowland",
                            Personality = "Darby",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 182.24020553189803,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 83,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Selena",
                            Personality = "Precious",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 941.15820448840725,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 84,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Duncan",
                            Personality = "Violet",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 174.16567476235744,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 85,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Karli",
                            Personality = "Olga",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 803.50501438896663,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 86,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Christophe",
                            Personality = "Edwardo",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 396.24212019809181,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 87,
                            EnclosureId = 25,
                            Gender = 0,
                            Name = "Effie",
                            Personality = "Cydney",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 966.11530222307499,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 88,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Rafaela",
                            Personality = "Wyatt",
                            PreferredDiet = "[]",
                            SpeciesId = 17,
                            Weight = 869.09809562821226,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 89,
                            EnclosureId = 4,
                            Gender = 1,
                            Name = "Shany",
                            Personality = "Wilson",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 643.11447832990302,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 90,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Briana",
                            Personality = "Camron",
                            PreferredDiet = "[]",
                            SpeciesId = 21,
                            Weight = 140.09924657684903,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 91,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Juanita",
                            Personality = "Brando",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 896.84622258741945,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 92,
                            EnclosureId = 19,
                            Gender = 0,
                            Name = "Heidi",
                            Personality = "Angelo",
                            PreferredDiet = "[]",
                            SpeciesId = 12,
                            Weight = 930.41293923685907,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 93,
                            EnclosureId = 3,
                            Gender = 1,
                            Name = "Hazle",
                            Personality = "Aida",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 334.05487861645145,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 94,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Miles",
                            Personality = "Trycia",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 785.46470224348172,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 95,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Nelda",
                            Personality = "Braeden",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 488.86943761631613,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 96,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Lorenzo",
                            Personality = "Graciela",
                            PreferredDiet = "[]",
                            SpeciesId = 12,
                            Weight = 624.15951958122264,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 97,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Samanta",
                            Personality = "Deja",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 504.83892052973101,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 98,
                            EnclosureId = 18,
                            Gender = 0,
                            Name = "Lavina",
                            Personality = "Tony",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 923.722905573866,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 99,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Jada",
                            Personality = "Alfonzo",
                            PreferredDiet = "[]",
                            SpeciesId = 19,
                            Weight = 652.63645862860426,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 100,
                            EnclosureId = 22,
                            Gender = 0,
                            Name = "Aurore",
                            Personality = "Hulda",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 716.53104385927156,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Accusamus consequatur eos atque doloremque iusto non nobis omnis culpa.",
                            Name = "suscipit",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Repellendus eos vero qui saepe sequi facere quam ad deserunt.",
                            Name = "aut",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Et laboriosam rem sequi harum voluptatem dolores aliquam alias illum.",
                            Name = "quos",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ad reiciendis possimus rerum nemo sequi dolorem voluptates animi magnam.",
                            Name = "sed",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Enim inventore qui aut dolore ea aut eum est perferendis.",
                            Name = "et",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Repellendus itaque velit repellendus et quam qui placeat molestiae dolores.",
                            Name = "et",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Quis sit fuga aut maiores mollitia dolore nam sed numquam.",
                            Name = "labore",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Id rerum aspernatur eum magni necessitatibus nisi enim eum facilis.",
                            Name = "at",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ut sit possimus possimus et sint tempora quis temporibus voluptas.",
                            Name = "beatae",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Blanditiis nisi autem sed consequuntur dolores illum similique perferendis molestiae.",
                            Name = "nostrum",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Consequatur voluptatem placeat tempora sed vero omnis architecto earum fugit.",
                            Name = "delectus",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Similique sunt dolorem facilis adipisci ut necessitatibus labore cumque nemo.",
                            Name = "temporibus",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Est inventore reprehenderit voluptatem ullam et voluptatibus aliquam et optio.",
                            Name = "iusto",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ipsa sint doloribus beatae sed hic aut nisi molestiae omnis.",
                            Name = "et",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Excepturi adipisci a neque qui aliquid explicabo eveniet aut impedit.",
                            Name = "in",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Et excepturi non voluptas id aspernatur sunt eum rerum harum.",
                            Name = "veniam",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Non porro tempore ducimus voluptas ut recusandae rerum molestiae ea.",
                            Name = "id",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Veritatis aut nobis necessitatibus sed ab illo sit perferendis expedita.",
                            Name = "voluptas",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "Alias dicta doloribus ut et omnis iusto dignissimos cum nam.",
                            Name = "in",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Quis quas explicabo alias itaque voluptatem beatae quo et optio.",
                            Name = "quia",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Quia veniam dicta eos magni eos iusto temporibus delectus dolorem.",
                            Name = "at",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 22,
                            Description = "Cumque adipisci blanditiis necessitatibus cumque voluptatem dolor similique enim sint.",
                            Name = "laborum",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Quis doloremque sunt voluptatibus ut velit vitae voluptas quibusdam modi.",
                            Name = "aut",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Mollitia sequi dignissimos quia maiores qui officia dolorum beatae ut.",
                            Name = "et",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 25,
                            Description = "Assumenda tenetur est consectetur voluptate ut recusandae commodi ad molestiae.",
                            Name = "quisquam",
                            ZooId = 2
                        });
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PredatorEnclosure")
                        .HasColumnType("bit");

                    b.Property<int>("PredatorSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorSpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 3,
                            Habitat = 16,
                            Name = "dicta",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 6,
                            SecurityRequired = 1,
                            Size = 234.96390556297578,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 2,
                            Climate = 4,
                            Habitat = 8,
                            Name = "et",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 23,
                            SecurityRequired = 3,
                            Size = 306.61589197491548,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Climate = 3,
                            Habitat = 4,
                            Name = "molestias",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 24,
                            SecurityRequired = 0,
                            Size = 837.16331606115625,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 4,
                            Climate = 1,
                            Habitat = 32,
                            Name = "commodi",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 19,
                            SecurityRequired = 3,
                            Size = 723.75837856281146,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Climate = 4,
                            Habitat = 8,
                            Name = "sit",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 18,
                            SecurityRequired = 0,
                            Size = 560.59287182775302,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 6,
                            Climate = 0,
                            Habitat = 2,
                            Name = "sequi",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 17,
                            SecurityRequired = 0,
                            Size = 523.04309804885759,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            Climate = 4,
                            Habitat = 16,
                            Name = "sit",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 22,
                            SecurityRequired = 0,
                            Size = 159.39853810295423,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Climate = 1,
                            Habitat = 32,
                            Name = "esse",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 4,
                            SecurityRequired = 1,
                            Size = 572.88527323274502,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Climate = 1,
                            Habitat = 64,
                            Name = "quo",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 25,
                            SecurityRequired = 0,
                            Size = 436.30925995390322,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 10,
                            Climate = 4,
                            Habitat = 32,
                            Name = "molestias",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 3,
                            SecurityRequired = 2,
                            Size = 539.5054466814928,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 11,
                            Climate = 1,
                            Habitat = 64,
                            Name = "harum",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 25,
                            SecurityRequired = 1,
                            Size = 813.60681358928423,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 12,
                            Climate = 2,
                            Habitat = 4,
                            Name = "eos",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 20,
                            SecurityRequired = 1,
                            Size = 672.52764294425333,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 13,
                            Climate = 2,
                            Habitat = 8,
                            Name = "rerum",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 8,
                            SecurityRequired = 2,
                            Size = 454.07986279900774,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 14,
                            Climate = 3,
                            Habitat = 1,
                            Name = "velit",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 2,
                            SecurityRequired = 0,
                            Size = 844.5389142214442,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 15,
                            Climate = 2,
                            Habitat = 16,
                            Name = "repellendus",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 20,
                            SecurityRequired = 2,
                            Size = 443.26104338002375,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 16,
                            Climate = 4,
                            Habitat = 1,
                            Name = "eos",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 6,
                            SecurityRequired = 2,
                            Size = 347.46907029182097,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 17,
                            Climate = 4,
                            Habitat = 64,
                            Name = "quos",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 13,
                            SecurityRequired = 0,
                            Size = 758.20058098276672,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 18,
                            Climate = 3,
                            Habitat = 8,
                            Name = "molestias",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 13,
                            SecurityRequired = 1,
                            Size = 292.21674437655776,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            Climate = 0,
                            Habitat = 32,
                            Name = "occaecati",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 19,
                            SecurityRequired = 3,
                            Size = 139.35034070584862,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 20,
                            Climate = 1,
                            Habitat = 16,
                            Name = "ratione",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 15,
                            SecurityRequired = 1,
                            Size = 883.01348247509179,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 21,
                            Climate = 4,
                            Habitat = 32,
                            Name = "aliquam",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 20,
                            SecurityRequired = 1,
                            Size = 687.76994852837504,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 22,
                            Climate = 0,
                            Habitat = 16,
                            Name = "error",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 4,
                            SecurityRequired = 0,
                            Size = 330.31628980751003,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            Climate = 1,
                            Habitat = 32,
                            Name = "libero",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 17,
                            SecurityRequired = 2,
                            Size = 397.54850085858686,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 24,
                            Climate = 0,
                            Habitat = 64,
                            Name = "repudiandae",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 2,
                            SecurityRequired = 2,
                            Size = 156.50678515321641,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 25,
                            Climate = 1,
                            Habitat = 1,
                            Name = "voluptas",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 22,
                            SecurityRequired = 1,
                            Size = 165.07002232282213,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<int>("Diet")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Predator")
                        .HasColumnType("bit");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequired")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Aquila chrysaetos",
                            Name = "Crocodile",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 1,
                            SpaceRequired = 32.01379880006678
                        },
                        new
                        {
                            Id = 2,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Ramphastos toco",
                            Name = "Meerkat",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 2,
                            SpaceRequired = 75.126026509475835
                        },
                        new
                        {
                            Id = 3,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Ursus maritimus",
                            Name = "Dolphin",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 0,
                            SpaceRequired = 44.712891972259158
                        },
                        new
                        {
                            Id = 4,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Panthera leo",
                            Name = "Octopus",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 4,
                            SpaceRequired = 25.07543072138046
                        },
                        new
                        {
                            Id = 5,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Manis javanica",
                            Name = "Bear",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 5,
                            SpaceRequired = 92.946270527946297
                        },
                        new
                        {
                            Id = 6,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Panthera onca",
                            Name = "Koala",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 1,
                            SpaceRequired = 90.171262429381557
                        },
                        new
                        {
                            Id = 7,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Hippopotamus amphibius",
                            Name = "Pangolin",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 0,
                            SpaceRequired = 11.058055322389976
                        },
                        new
                        {
                            Id = 8,
                            Activity = 0,
                            Diet = 4,
                            LatinName = "Diceros bicornis",
                            Name = "Cheetah",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 2,
                            SpaceRequired = 69.602043105203734
                        },
                        new
                        {
                            Id = 9,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Panthera leo",
                            Name = "Puma",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 3,
                            SpaceRequired = 50.729378722585103
                        },
                        new
                        {
                            Id = 10,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Strix aluco",
                            Name = "Gorilla",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 1,
                            SpaceRequired = 55.533285033392076
                        },
                        new
                        {
                            Id = 11,
                            Activity = 0,
                            Diet = 1,
                            LatinName = "Crocodylus niloticus",
                            Name = "Jaguar",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 2,
                            SpaceRequired = 28.066075392286631
                        },
                        new
                        {
                            Id = 12,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Suricata suricatta",
                            Name = "Kangaroo",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 3,
                            SpaceRequired = 24.891701966967656
                        },
                        new
                        {
                            Id = 13,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Puma concolor",
                            Name = "Koala",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 5,
                            SpaceRequired = 86.18516549729182
                        },
                        new
                        {
                            Id = 14,
                            Activity = 0,
                            Diet = 2,
                            LatinName = "Aquila chrysaetos",
                            Name = "Tiger",
                            Predator = false,
                            SecurityRequired = 1,
                            Size = 2,
                            SpaceRequired = 59.966173743980853
                        },
                        new
                        {
                            Id = 15,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Aquila chrysaetos",
                            Name = "Penguin",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 5,
                            SpaceRequired = 78.273665188828033
                        },
                        new
                        {
                            Id = 16,
                            Activity = 0,
                            Diet = 2,
                            LatinName = "Hippopotamus amphibius",
                            Name = "Penguin",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 5,
                            SpaceRequired = 61.959120927809764
                        },
                        new
                        {
                            Id = 17,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Aquila chrysaetos",
                            Name = "Dolphin",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 0,
                            SpaceRequired = 31.378917859086741
                        },
                        new
                        {
                            Id = 18,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Tursiops truncatus",
                            Name = "Squirrel",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 2,
                            SpaceRequired = 73.372082847472058
                        },
                        new
                        {
                            Id = 19,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Canis lupus",
                            Name = "Tiger",
                            Predator = false,
                            SecurityRequired = 1,
                            Size = 1,
                            SpaceRequired = 11.049173388316213
                        },
                        new
                        {
                            Id = 20,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Panthera tigris",
                            Name = "Owl",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 5,
                            SpaceRequired = 10.002188366514011
                        },
                        new
                        {
                            Id = 21,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Loxodonta africana",
                            Name = "Octopus",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 4,
                            SpaceRequired = 84.254124300851643
                        },
                        new
                        {
                            Id = 22,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Diceros bicornis",
                            Name = "Squirrel",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 3,
                            SpaceRequired = 22.567867948564974
                        },
                        new
                        {
                            Id = 23,
                            Activity = 2,
                            Diet = 3,
                            LatinName = "Macropus giganteus",
                            Name = "Octopus",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 5,
                            SpaceRequired = 30.545153512919448
                        },
                        new
                        {
                            Id = 24,
                            Activity = 0,
                            Diet = 2,
                            LatinName = "Gorilla beringei",
                            Name = "Puma",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 1,
                            SpaceRequired = 44.315077930130165
                        },
                        new
                        {
                            Id = 25,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Canis lupus",
                            Name = "Rhino",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 4,
                            SpaceRequired = 99.159189397346665
                        });
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZooModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "East Alexanne",
                            Country = "Comoros",
                            Description = "Est neque est id officia.",
                            Name = "Wolf Group"
                        },
                        new
                        {
                            Id = 2,
                            City = "North Madelynshire",
                            Country = "Saint Vincent and the Grenadines",
                            Description = "Et distinctio dignissimos aut sed.",
                            Name = "Macejkovic - Prohaska"
                        });
                });

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.HasOne("Zoo.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.HasOne("Zoo.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Categories")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.HasOne("Zoo.Models.Species", "PredatorSpecies")
                        .WithMany()
                        .HasForeignKey("PredatorSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredatorSpecies");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Categories");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
