// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Data;

#nullable disable

namespace Zoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20240628131216_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CategorySpecies");
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Tre",
                            Personality = "Winona",
                            PreferredDiet = "ab",
                            SpeciesId = 19,
                            Weight = 417.57281798920246,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnclosureId = 23,
                            Gender = 0,
                            Name = "Ezekiel",
                            Personality = "Eulalia",
                            PreferredDiet = "a",
                            SpeciesId = 25,
                            Weight = 815.98435927800051,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnclosureId = 10,
                            Gender = 1,
                            Name = "Jessyca",
                            Personality = "Salma",
                            PreferredDiet = "sapiente",
                            SpeciesId = 12,
                            Weight = 721.83488853471715,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Alexandrine",
                            Personality = "Julia",
                            PreferredDiet = "saepe",
                            SpeciesId = 15,
                            Weight = 210.87323460397315,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnclosureId = 22,
                            Gender = 1,
                            Name = "Destany",
                            Personality = "Kendrick",
                            PreferredDiet = "voluptatem",
                            SpeciesId = 6,
                            Weight = 641.91768883000304,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 6,
                            EnclosureId = 10,
                            Gender = 0,
                            Name = "Tyson",
                            Personality = "Desiree",
                            PreferredDiet = "vel",
                            SpeciesId = 14,
                            Weight = 665.70962448646605,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Margarita",
                            Personality = "Tony",
                            PreferredDiet = "molestiae",
                            SpeciesId = 23,
                            Weight = 417.37804352687544,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            EnclosureId = 22,
                            Gender = 0,
                            Name = "Melyna",
                            Personality = "Bryon",
                            PreferredDiet = "aspernatur",
                            SpeciesId = 22,
                            Weight = 501.76167923731902,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            EnclosureId = 17,
                            Gender = 1,
                            Name = "Daryl",
                            Personality = "Camren",
                            PreferredDiet = "assumenda",
                            SpeciesId = 18,
                            Weight = 241.74392120140982,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Stone",
                            Personality = "Alverta",
                            PreferredDiet = "impedit",
                            SpeciesId = 15,
                            Weight = 515.05365393158752,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Doyle",
                            Personality = "Tito",
                            PreferredDiet = "eos",
                            SpeciesId = 5,
                            Weight = 428.92397565770773,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 12,
                            EnclosureId = 13,
                            Gender = 1,
                            Name = "Harrison",
                            Personality = "Gianni",
                            PreferredDiet = "nulla",
                            SpeciesId = 11,
                            Weight = 480.75350180712292,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 13,
                            EnclosureId = 22,
                            Gender = 0,
                            Name = "Daisha",
                            Personality = "Ida",
                            PreferredDiet = "vero",
                            SpeciesId = 13,
                            Weight = 957.17396537914135,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 14,
                            EnclosureId = 12,
                            Gender = 0,
                            Name = "Cayla",
                            Personality = "Reva",
                            PreferredDiet = "sint",
                            SpeciesId = 10,
                            Weight = 961.21940422540627,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            EnclosureId = 21,
                            Gender = 0,
                            Name = "Emery",
                            Personality = "Kyla",
                            PreferredDiet = "est",
                            SpeciesId = 13,
                            Weight = 506.30727382070899,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 16,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Ivy",
                            Personality = "Keeley",
                            PreferredDiet = "aut",
                            SpeciesId = 3,
                            Weight = 954.48089392191764,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Estelle",
                            Personality = "Emerald",
                            PreferredDiet = "omnis",
                            SpeciesId = 15,
                            Weight = 239.90378845742123,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 18,
                            EnclosureId = 10,
                            Gender = 0,
                            Name = "Pearline",
                            Personality = "Vesta",
                            PreferredDiet = "nam",
                            SpeciesId = 3,
                            Weight = 122.97417102846829,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 19,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Melba",
                            Personality = "Maddison",
                            PreferredDiet = "itaque",
                            SpeciesId = 6,
                            Weight = 568.73404773975756,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 20,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Novella",
                            Personality = "Jasper",
                            PreferredDiet = "quis",
                            SpeciesId = 23,
                            Weight = 744.92792915732173,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 21,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Paris",
                            Personality = "Gail",
                            PreferredDiet = "nam",
                            SpeciesId = 1,
                            Weight = 568.64896161335582,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            EnclosureId = 12,
                            Gender = 0,
                            Name = "Alvena",
                            Personality = "Cecile",
                            PreferredDiet = "voluptate",
                            SpeciesId = 8,
                            Weight = 152.78184149692169,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 23,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Darrion",
                            Personality = "Velva",
                            PreferredDiet = "animi",
                            SpeciesId = 21,
                            Weight = 881.24014090216917,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 24,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Adolfo",
                            Personality = "Caleb",
                            PreferredDiet = "fugiat",
                            SpeciesId = 23,
                            Weight = 135.47559532029311,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 25,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Collin",
                            Personality = "Jaylin",
                            PreferredDiet = "et",
                            SpeciesId = 7,
                            Weight = 169.1017460855748,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 26,
                            EnclosureId = 10,
                            Gender = 0,
                            Name = "Antwan",
                            Personality = "Lilian",
                            PreferredDiet = "voluptatum",
                            SpeciesId = 13,
                            Weight = 374.07152090890003,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 27,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Cayla",
                            Personality = "Julian",
                            PreferredDiet = "porro",
                            SpeciesId = 5,
                            Weight = 352.7969952371638,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 28,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Adrien",
                            Personality = "Bailey",
                            PreferredDiet = "ullam",
                            SpeciesId = 22,
                            Weight = 187.53713855231032,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 29,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Devyn",
                            Personality = "Cynthia",
                            PreferredDiet = "earum",
                            SpeciesId = 4,
                            Weight = 563.45683794562717,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 30,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Aaron",
                            Personality = "Vicky",
                            PreferredDiet = "molestias",
                            SpeciesId = 12,
                            Weight = 742.00323463910001,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 31,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Davion",
                            Personality = "Kenna",
                            PreferredDiet = "veritatis",
                            SpeciesId = 21,
                            Weight = 824.99335848312444,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 32,
                            EnclosureId = 22,
                            Gender = 0,
                            Name = "Brannon",
                            Personality = "Karianne",
                            PreferredDiet = "qui",
                            SpeciesId = 20,
                            Weight = 597.95568319700567,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 33,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Myah",
                            Personality = "Carissa",
                            PreferredDiet = "praesentium",
                            SpeciesId = 24,
                            Weight = 979.10842881058568,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 34,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Duane",
                            Personality = "Robyn",
                            PreferredDiet = "iure",
                            SpeciesId = 1,
                            Weight = 895.92522508477168,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 35,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Hilda",
                            Personality = "Ed",
                            PreferredDiet = "rerum",
                            SpeciesId = 25,
                            Weight = 26.961195020253317,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 36,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Jamel",
                            Personality = "Violette",
                            PreferredDiet = "aut",
                            SpeciesId = 22,
                            Weight = 508.03508299116976,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 37,
                            EnclosureId = 18,
                            Gender = 0,
                            Name = "Haley",
                            Personality = "Olga",
                            PreferredDiet = "iste",
                            SpeciesId = 18,
                            Weight = 567.49883771065777,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 38,
                            EnclosureId = 24,
                            Gender = 0,
                            Name = "Kaitlyn",
                            Personality = "Jewel",
                            PreferredDiet = "dolorem",
                            SpeciesId = 9,
                            Weight = 138.06514507065151,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 39,
                            EnclosureId = 11,
                            Gender = 1,
                            Name = "Esteban",
                            Personality = "Ulices",
                            PreferredDiet = "cum",
                            SpeciesId = 14,
                            Weight = 711.25888368915003,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 40,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Dedric",
                            Personality = "Lelia",
                            PreferredDiet = "dolorem",
                            SpeciesId = 24,
                            Weight = 267.43802218087825,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 41,
                            EnclosureId = 25,
                            Gender = 1,
                            Name = "Fredy",
                            Personality = "Wilson",
                            PreferredDiet = "voluptatibus",
                            SpeciesId = 7,
                            Weight = 593.86866893888225,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 42,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Jerome",
                            Personality = "Einar",
                            PreferredDiet = "et",
                            SpeciesId = 3,
                            Weight = 993.98901477182733,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 43,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Lorena",
                            Personality = "Javon",
                            PreferredDiet = "officia",
                            SpeciesId = 18,
                            Weight = 519.32607825869184,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 44,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Una",
                            Personality = "Waylon",
                            PreferredDiet = "est",
                            SpeciesId = 11,
                            Weight = 279.13041176630418,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 45,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Marianna",
                            Personality = "Amiya",
                            PreferredDiet = "praesentium",
                            SpeciesId = 23,
                            Weight = 421.70991409334806,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 46,
                            EnclosureId = 24,
                            Gender = 1,
                            Name = "Maudie",
                            Personality = "Howell",
                            PreferredDiet = "maiores",
                            SpeciesId = 25,
                            Weight = 234.32013599149712,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 47,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Florine",
                            Personality = "Deon",
                            PreferredDiet = "corrupti",
                            SpeciesId = 13,
                            Weight = 334.4332111043301,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 48,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Prudence",
                            Personality = "Jacques",
                            PreferredDiet = "et",
                            SpeciesId = 14,
                            Weight = 636.41280965164231,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 49,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Yasmin",
                            Personality = "Kailyn",
                            PreferredDiet = "quia",
                            SpeciesId = 14,
                            Weight = 25.340012376290993,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 50,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Mabelle",
                            Personality = "Madelyn",
                            PreferredDiet = "quas",
                            SpeciesId = 13,
                            Weight = 635.79369425270977,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 51,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Anthony",
                            Personality = "Rocky",
                            PreferredDiet = "cupiditate",
                            SpeciesId = 15,
                            Weight = 872.968602151391,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 52,
                            EnclosureId = 17,
                            Gender = 1,
                            Name = "Tillman",
                            Personality = "Xzavier",
                            PreferredDiet = "eum",
                            SpeciesId = 14,
                            Weight = 940.79482447515045,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 53,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "William",
                            Personality = "Janick",
                            PreferredDiet = "aut",
                            SpeciesId = 13,
                            Weight = 114.13077909170514,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 54,
                            EnclosureId = 22,
                            Gender = 0,
                            Name = "Bessie",
                            Personality = "Carissa",
                            PreferredDiet = "quo",
                            SpeciesId = 19,
                            Weight = 969.65887307250932,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 55,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Laverne",
                            Personality = "Ismael",
                            PreferredDiet = "rerum",
                            SpeciesId = 8,
                            Weight = 838.72223726086952,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 56,
                            EnclosureId = 12,
                            Gender = 0,
                            Name = "Keyon",
                            Personality = "Augustus",
                            PreferredDiet = "quis",
                            SpeciesId = 3,
                            Weight = 327.81627743895217,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 57,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Donna",
                            Personality = "Patricia",
                            PreferredDiet = "excepturi",
                            SpeciesId = 13,
                            Weight = 242.63359572966863,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 58,
                            EnclosureId = 13,
                            Gender = 0,
                            Name = "Schuyler",
                            Personality = "Adam",
                            PreferredDiet = "voluptates",
                            SpeciesId = 5,
                            Weight = 140.57536597982349,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 59,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Murray",
                            Personality = "Marietta",
                            PreferredDiet = "voluptatem",
                            SpeciesId = 9,
                            Weight = 45.159556334491789,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 60,
                            EnclosureId = 20,
                            Gender = 1,
                            Name = "Kyra",
                            Personality = "Gabrielle",
                            PreferredDiet = "voluptatibus",
                            SpeciesId = 1,
                            Weight = 499.26101626569209,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 61,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Erik",
                            Personality = "Burnice",
                            PreferredDiet = "ipsam",
                            SpeciesId = 23,
                            Weight = 261.47679231662147,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 62,
                            EnclosureId = 10,
                            Gender = 1,
                            Name = "D'angelo",
                            Personality = "Autumn",
                            PreferredDiet = "omnis",
                            SpeciesId = 17,
                            Weight = 530.80326657876401,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 63,
                            EnclosureId = 3,
                            Gender = 1,
                            Name = "Bulah",
                            Personality = "Lawrence",
                            PreferredDiet = "aut",
                            SpeciesId = 16,
                            Weight = 526.90167515966959,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 64,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Isaac",
                            Personality = "Jamaal",
                            PreferredDiet = "dignissimos",
                            SpeciesId = 23,
                            Weight = 663.92035962518844,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 65,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Wilburn",
                            Personality = "Schuyler",
                            PreferredDiet = "facilis",
                            SpeciesId = 12,
                            Weight = 642.07117492801819,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 66,
                            EnclosureId = 25,
                            Gender = 0,
                            Name = "Josianne",
                            Personality = "Clare",
                            PreferredDiet = "sunt",
                            SpeciesId = 1,
                            Weight = 34.005131141671484,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 67,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Esther",
                            Personality = "Buford",
                            PreferredDiet = "eum",
                            SpeciesId = 15,
                            Weight = 546.4197261663694,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 68,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Avis",
                            Personality = "Cora",
                            PreferredDiet = "rem",
                            SpeciesId = 15,
                            Weight = 275.67698448262655,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 69,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Rahul",
                            Personality = "Mack",
                            PreferredDiet = "ab",
                            SpeciesId = 10,
                            Weight = 547.34195193200651,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 70,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Mariela",
                            Personality = "Faye",
                            PreferredDiet = "quasi",
                            SpeciesId = 23,
                            Weight = 796.98526232513211,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 71,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Beau",
                            Personality = "Mervin",
                            PreferredDiet = "sit",
                            SpeciesId = 4,
                            Weight = 358.45742108987594,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 72,
                            EnclosureId = 10,
                            Gender = 1,
                            Name = "Francesco",
                            Personality = "Thelma",
                            PreferredDiet = "quis",
                            SpeciesId = 23,
                            Weight = 895.60520303931878,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 73,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Dylan",
                            Personality = "Brock",
                            PreferredDiet = "ea",
                            SpeciesId = 9,
                            Weight = 155.57270878800966,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 74,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Chelsea",
                            Personality = "Sheridan",
                            PreferredDiet = "in",
                            SpeciesId = 1,
                            Weight = 917.00670023474481,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 75,
                            EnclosureId = 3,
                            Gender = 1,
                            Name = "Naomi",
                            Personality = "Anika",
                            PreferredDiet = "quam",
                            SpeciesId = 15,
                            Weight = 937.437552724856,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 76,
                            EnclosureId = 25,
                            Gender = 0,
                            Name = "Margot",
                            Personality = "Angeline",
                            PreferredDiet = "tenetur",
                            SpeciesId = 19,
                            Weight = 286.35590842331453,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 77,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Travon",
                            Personality = "Alanis",
                            PreferredDiet = "incidunt",
                            SpeciesId = 6,
                            Weight = 508.02877502412838,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 78,
                            EnclosureId = 14,
                            Gender = 0,
                            Name = "Jeromy",
                            Personality = "Chaim",
                            PreferredDiet = "voluptas",
                            SpeciesId = 21,
                            Weight = 672.76438323437435,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 79,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Ariel",
                            Personality = "Eloy",
                            PreferredDiet = "temporibus",
                            SpeciesId = 7,
                            Weight = 822.37751072449805,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 80,
                            EnclosureId = 13,
                            Gender = 1,
                            Name = "Maurice",
                            Personality = "Dixie",
                            PreferredDiet = "nulla",
                            SpeciesId = 22,
                            Weight = 395.70780683391104,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 81,
                            EnclosureId = 22,
                            Gender = 1,
                            Name = "Elmo",
                            Personality = "Lysanne",
                            PreferredDiet = "recusandae",
                            SpeciesId = 6,
                            Weight = 954.00789222292951,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 82,
                            EnclosureId = 12,
                            Gender = 0,
                            Name = "Jacky",
                            Personality = "Alfonso",
                            PreferredDiet = "aut",
                            SpeciesId = 15,
                            Weight = 928.29145441694823,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 83,
                            EnclosureId = 10,
                            Gender = 1,
                            Name = "Fletcher",
                            Personality = "Gillian",
                            PreferredDiet = "voluptate",
                            SpeciesId = 24,
                            Weight = 474.12028968247154,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 84,
                            EnclosureId = 19,
                            Gender = 0,
                            Name = "Alejandrin",
                            Personality = "Kelton",
                            PreferredDiet = "nulla",
                            SpeciesId = 3,
                            Weight = 629.08061988150894,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 85,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Lorenz",
                            Personality = "Lavinia",
                            PreferredDiet = "quia",
                            SpeciesId = 23,
                            Weight = 260.75152364578889,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 86,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Annalise",
                            Personality = "Katlynn",
                            PreferredDiet = "eos",
                            SpeciesId = 11,
                            Weight = 667.35110831724444,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 87,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Jayme",
                            Personality = "Marvin",
                            PreferredDiet = "iure",
                            SpeciesId = 5,
                            Weight = 23.018832861395399,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 88,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Miracle",
                            Personality = "Reginald",
                            PreferredDiet = "quia",
                            SpeciesId = 18,
                            Weight = 776.90767706020165,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 89,
                            EnclosureId = 21,
                            Gender = 0,
                            Name = "Neal",
                            Personality = "Niko",
                            PreferredDiet = "modi",
                            SpeciesId = 14,
                            Weight = 244.7696809641364,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 90,
                            EnclosureId = 13,
                            Gender = 0,
                            Name = "Carolina",
                            Personality = "Rex",
                            PreferredDiet = "perferendis",
                            SpeciesId = 10,
                            Weight = 595.61260876609265,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 91,
                            EnclosureId = 10,
                            Gender = 0,
                            Name = "Oceane",
                            Personality = "Percy",
                            PreferredDiet = "sit",
                            SpeciesId = 15,
                            Weight = 754.41434744348089,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 92,
                            EnclosureId = 24,
                            Gender = 1,
                            Name = "Zachariah",
                            Personality = "Eileen",
                            PreferredDiet = "est",
                            SpeciesId = 4,
                            Weight = 104.32656018210876,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 93,
                            EnclosureId = 12,
                            Gender = 0,
                            Name = "Janessa",
                            Personality = "Ewald",
                            PreferredDiet = "sint",
                            SpeciesId = 25,
                            Weight = 906.84249251277765,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 94,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Lizzie",
                            Personality = "Dexter",
                            PreferredDiet = "quia",
                            SpeciesId = 2,
                            Weight = 506.23335387509843,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 95,
                            EnclosureId = 20,
                            Gender = 0,
                            Name = "Marcella",
                            Personality = "Orland",
                            PreferredDiet = "aut",
                            SpeciesId = 22,
                            Weight = 17.288391151834666,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 96,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Emmalee",
                            Personality = "Brooke",
                            PreferredDiet = "fugit",
                            SpeciesId = 21,
                            Weight = 717.31817468939948,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 97,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Albin",
                            Personality = "Pasquale",
                            PreferredDiet = "voluptas",
                            SpeciesId = 14,
                            Weight = 40.8357868659781,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 98,
                            EnclosureId = 15,
                            Gender = 0,
                            Name = "Cordelia",
                            Personality = "Yesenia",
                            PreferredDiet = "magnam",
                            SpeciesId = 6,
                            Weight = 981.70194264585416,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 99,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Alycia",
                            Personality = "Danika",
                            PreferredDiet = "eligendi",
                            SpeciesId = 4,
                            Weight = 952.86616423740338,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 100,
                            EnclosureId = 13,
                            Gender = 1,
                            Name = "Lindsay",
                            Personality = "Keara",
                            PreferredDiet = "et",
                            SpeciesId = 2,
                            Weight = 607.90420992059444,
                            ZooId = 2
                        });
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quia sapiente labore maiores consequatur praesentium quos eos sed recusandae.",
                            Name = "impedit",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Deserunt magni aut sunt culpa quia iure blanditiis debitis consequatur.",
                            Name = "ex",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vitae deleniti aut illo perspiciatis laborum doloremque enim aut voluptatem.",
                            Name = "corrupti",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ut et vel voluptas qui voluptates quia ut ipsam fuga.",
                            Name = "similique",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Enim velit aperiam cum omnis est error molestias libero quis.",
                            Name = "quo",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Voluptas accusantium eius fugiat qui sit officia ut ipsum quo.",
                            Name = "earum",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dolores molestias nihil natus qui ipsa id exercitationem qui et.",
                            Name = "voluptates",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Dolores sed sit commodi id quod sunt qui enim omnis.",
                            Name = "asperiores",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Libero illum error sit maxime architecto laboriosam sunt doloribus fugit.",
                            Name = "dolorem",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cum provident quibusdam repudiandae aut consequatur cupiditate natus architecto voluptates.",
                            Name = "sed",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Odio et explicabo in magni repudiandae dolorem doloribus modi sed.",
                            Name = "quidem",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Unde ut earum aut praesentium non fugiat excepturi ut libero.",
                            Name = "placeat",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Enim rem perferendis hic ea fugit distinctio sunt ipsa quisquam.",
                            Name = "nisi",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Voluptas quibusdam similique qui in facere nihil hic nobis unde.",
                            Name = "officiis",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ut vero architecto deserunt quo nobis voluptatem qui rem odio.",
                            Name = "rem",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Qui quas cupiditate non nisi fugiat sapiente autem officiis id.",
                            Name = "aut",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Aspernatur dolorem velit accusantium non libero voluptatibus distinctio occaecati qui.",
                            Name = "sapiente",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Eum rerum dolorem et pariatur illum voluptas et vitae et.",
                            Name = "aut",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ullam labore impedit velit quod nam animi aut mollitia explicabo.",
                            Name = "officiis",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Optio sunt perspiciatis voluptatem nobis reprehenderit soluta laboriosam alias qui.",
                            Name = "facere",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Dolorem incidunt sunt et dolores nulla illum velit nihil et.",
                            Name = "rem",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 22,
                            Description = "Sint facilis et eaque occaecati sint quam porro officia harum.",
                            Name = "tempore",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Saepe nostrum officia repudiandae saepe amet officia iure expedita incidunt.",
                            Name = "non",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Praesentium ex aut tenetur sint dignissimos illo velit sed quis.",
                            Name = "vel",
                            ZooId = 2
                        },
                        new
                        {
                            Id = 25,
                            Description = "Quidem aut qui nam maiores autem iusto voluptatem quo voluptatem.",
                            Name = "modi",
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PredatorEnclosure")
                        .HasColumnType("bit");

                    b.Property<int?>("PredatorSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int?>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorSpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 2,
                            Habitat = 32,
                            Name = "maxime",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 10,
                            SecurityRequired = 0,
                            Size = 739.14117660645536,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 2,
                            Climate = 4,
                            Habitat = 64,
                            Name = "ratione",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 15,
                            SecurityRequired = 0,
                            Size = 290.66013764848117,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Climate = 2,
                            Habitat = 16,
                            Name = "et",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 18,
                            SecurityRequired = 2,
                            Size = 816.99306410165514,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 4,
                            Climate = 0,
                            Habitat = 16,
                            Name = "dignissimos",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 11,
                            SecurityRequired = 1,
                            Size = 298.20218968918215,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 5,
                            Climate = 1,
                            Habitat = 4,
                            Name = "est",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 13,
                            SecurityRequired = 0,
                            Size = 892.7911638665521,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            Climate = 1,
                            Habitat = 4,
                            Name = "rem",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 7,
                            SecurityRequired = 1,
                            Size = 565.06147664013815,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 7,
                            Climate = 4,
                            Habitat = 32,
                            Name = "et",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 12,
                            SecurityRequired = 2,
                            Size = 261.77816976129571,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 8,
                            Climate = 4,
                            Habitat = 8,
                            Name = "vero",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 12,
                            SecurityRequired = 2,
                            Size = 943.42953697461292,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Climate = 4,
                            Habitat = 8,
                            Name = "officiis",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 18,
                            SecurityRequired = 0,
                            Size = 974.29656399582507,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Climate = 4,
                            Habitat = 4,
                            Name = "sed",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 1,
                            SecurityRequired = 2,
                            Size = 549.18105871867294,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 11,
                            Climate = 3,
                            Habitat = 32,
                            Name = "dicta",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 20,
                            SecurityRequired = 1,
                            Size = 531.51722324512752,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 12,
                            Climate = 0,
                            Habitat = 4,
                            Name = "ex",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 4,
                            SecurityRequired = 1,
                            Size = 535.91156757817271,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            Climate = 3,
                            Habitat = 32,
                            Name = "labore",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 17,
                            SecurityRequired = 2,
                            Size = 758.72320953566179,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            Climate = 0,
                            Habitat = 4,
                            Name = "et",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 25,
                            SecurityRequired = 1,
                            Size = 994.90559536546948,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            Climate = 4,
                            Habitat = 8,
                            Name = "aut",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 14,
                            SecurityRequired = 0,
                            Size = 999.44367061607329,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            Climate = 3,
                            Habitat = 32,
                            Name = "esse",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 13,
                            SecurityRequired = 1,
                            Size = 798.58878076463384,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            Climate = 4,
                            Habitat = 1,
                            Name = "occaecati",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 1,
                            SecurityRequired = 0,
                            Size = 398.70315091848965,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 18,
                            Climate = 4,
                            Habitat = 16,
                            Name = "perspiciatis",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 8,
                            SecurityRequired = 0,
                            Size = 553.22519368490714,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            Climate = 0,
                            Habitat = 32,
                            Name = "adipisci",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 11,
                            SecurityRequired = 2,
                            Size = 131.19063911747622,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            Climate = 0,
                            Habitat = 1,
                            Name = "voluptas",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 9,
                            SecurityRequired = 1,
                            Size = 101.01454371040934,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 21,
                            Climate = 0,
                            Habitat = 1,
                            Name = "praesentium",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 20,
                            SecurityRequired = 0,
                            Size = 345.19538992076968,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            Climate = 4,
                            Habitat = 2,
                            Name = "id",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 9,
                            SecurityRequired = 2,
                            Size = 933.33741540363246,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 23,
                            Climate = 0,
                            Habitat = 4,
                            Name = "aut",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 7,
                            SecurityRequired = 2,
                            Size = 357.87812210291122,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 24,
                            Climate = 3,
                            Habitat = 32,
                            Name = "non",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 15,
                            SecurityRequired = 2,
                            Size = 347.69429511964432,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 25,
                            Climate = 0,
                            Habitat = 1,
                            Name = "fugit",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 10,
                            SecurityRequired = 0,
                            Size = 863.70056503028093,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<int>("Diet")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Predator")
                        .HasColumnType("bit");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequired")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Crocodylus niloticus",
                            Name = "Toucan",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 2,
                            SpaceRequired = 26.265220187351421
                        },
                        new
                        {
                            Id = 2,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Phascolarctos cinereus",
                            Name = "Fox",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 0,
                            SpaceRequired = 31.860472652956048
                        },
                        new
                        {
                            Id = 3,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Panthera leo",
                            Name = "Chameleon",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 0,
                            SpaceRequired = 62.489454896109741
                        },
                        new
                        {
                            Id = 4,
                            Activity = 0,
                            Diet = 4,
                            LatinName = "Chamaeleo chamaeleon",
                            Name = "Lion",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 3,
                            SpaceRequired = 18.005875061787584
                        },
                        new
                        {
                            Id = 5,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Loxodonta africana",
                            Name = "Jaguar",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 1,
                            SpaceRequired = 18.96651192974354
                        },
                        new
                        {
                            Id = 6,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Bradypus variegatus",
                            Name = "Chameleon",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 0,
                            SpaceRequired = 95.789928874054667
                        },
                        new
                        {
                            Id = 7,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Ursus arctos",
                            Name = "Gorilla",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 5,
                            SpaceRequired = 99.663988367476762
                        },
                        new
                        {
                            Id = 8,
                            Activity = 2,
                            Diet = 2,
                            LatinName = "Equus quagga",
                            Name = "Penguin",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 5,
                            SpaceRequired = 30.689674688602633
                        },
                        new
                        {
                            Id = 9,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Loxodonta africana",
                            Name = "Kangaroo",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 5,
                            SpaceRequired = 88.493456828554429
                        },
                        new
                        {
                            Id = 10,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Diceros bicornis",
                            Name = "Koala",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 80.535567838518332
                        },
                        new
                        {
                            Id = 11,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Suricata suricatta",
                            Name = "Meerkat",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 41.590371195477822
                        },
                        new
                        {
                            Id = 12,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Panthera tigris",
                            Name = "Kangaroo",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 0,
                            SpaceRequired = 53.598798018464464
                        },
                        new
                        {
                            Id = 13,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Gorilla beringei",
                            Name = "Fox",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 4,
                            SpaceRequired = 46.661610839769594
                        },
                        new
                        {
                            Id = 14,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Vulpes vulpes",
                            Name = "Crocodile",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 4,
                            SpaceRequired = 29.947167983984883
                        },
                        new
                        {
                            Id = 15,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Diceros bicornis",
                            Name = "Pangolin",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 3,
                            SpaceRequired = 97.151060150544552
                        },
                        new
                        {
                            Id = 16,
                            Activity = 0,
                            Diet = 4,
                            LatinName = "Hippopotamus amphibius",
                            Name = "Fox",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 4,
                            SpaceRequired = 42.337182267485687
                        },
                        new
                        {
                            Id = 17,
                            Activity = 0,
                            Diet = 4,
                            LatinName = "Hippopotamus amphibius",
                            Name = "Chameleon",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 3,
                            SpaceRequired = 58.483152235198887
                        },
                        new
                        {
                            Id = 18,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Puma concolor",
                            Name = "Lion",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 4,
                            SpaceRequired = 94.566381516379963
                        },
                        new
                        {
                            Id = 19,
                            Activity = 0,
                            Diet = 4,
                            LatinName = "Puma concolor",
                            Name = "Elephant",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 4,
                            SpaceRequired = 12.991760782913598
                        },
                        new
                        {
                            Id = 20,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Puma concolor",
                            Name = "Chameleon",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 3,
                            SpaceRequired = 86.568349547555897
                        },
                        new
                        {
                            Id = 21,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Ursus arctos",
                            Name = "Tiger",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 80.338496868389853
                        },
                        new
                        {
                            Id = 22,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Ramphastos toco",
                            Name = "Lion",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 4,
                            SpaceRequired = 69.281953786552819
                        },
                        new
                        {
                            Id = 23,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Ramphastos toco",
                            Name = "Fox",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 1,
                            SpaceRequired = 78.886521232476852
                        },
                        new
                        {
                            Id = 24,
                            Activity = 0,
                            Diet = 4,
                            LatinName = "Hippopotamus amphibius",
                            Name = "Panda",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 4,
                            SpaceRequired = 99.935645162497735
                        },
                        new
                        {
                            Id = 25,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Canis lupus",
                            Name = "Zebra",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 4,
                            SpaceRequired = 64.205178167988606
                        });
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZooModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hesterberg",
                            Country = "United States of America",
                            Description = "Quibusdam suscipit dolores laboriosam in.",
                            Name = "Erdman and Sons"
                        },
                        new
                        {
                            Id = 2,
                            City = "North Fabianland",
                            Country = "Uganda",
                            Description = "Facilis perferendis quos ad commodi.",
                            Name = "Cummings, Kuhlman and Willms"
                        });
                });

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.HasOne("Zoo.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.HasOne("Zoo.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId");

                    b.HasOne("Zoo.Models.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Categories")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.HasOne("Zoo.Models.Species", "PredatorSpecies")
                        .WithMany()
                        .HasForeignKey("PredatorSpeciesId");

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId");

                    b.Navigation("PredatorSpecies");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Categories");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
