// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Data;

#nullable disable

namespace Zoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20240701153014_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CategorySpecies");
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Juwan",
                            Personality = "red",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 770.43921588456078,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Joel",
                            Personality = "cyan",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 324.83921302471271,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            EnclosureId = 21,
                            Gender = 0,
                            Name = "Terrance",
                            Personality = "white",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 172.91626549195399,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Devin",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 81.69294725307995,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Mylene",
                            Personality = "ivory",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 923.53142513173555,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Reid",
                            Personality = "black",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 33.58784554949321,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Beulah",
                            Personality = "magenta",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 714.26192512849673,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Sven",
                            Personality = "azure",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 159.19456692233697,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Madisyn",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 980.32049214587971,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Sabrina",
                            Personality = "silver",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 775.72359527862102,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            EnclosureId = 23,
                            Gender = 1,
                            Name = "Rylan",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 968.6819243291186,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Raquel",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 117.47190016503384,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Janet",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 1,
                            Weight = 239.52794279700672,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Keara",
                            Personality = "orange",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 175.17142335845435,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Jerad",
                            Personality = "ivory",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 645.2166605889679,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Lacy",
                            Personality = "violet",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 580.48708777896616,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Camilla",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 965.60004227360935,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 18,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Unique",
                            Personality = "lime",
                            PreferredDiet = "[]",
                            SpeciesId = 1,
                            Weight = 49.570340618931411,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            EnclosureId = 23,
                            Gender = 1,
                            Name = "Destiny",
                            Personality = "azure",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 227.64016287885684,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Tia",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 567.48026872222556,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 21,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Chandler",
                            Personality = "indigo",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 355.86415464176417,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Judy",
                            Personality = "yellow",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 54.774409449140158,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            EnclosureId = 16,
                            Gender = 0,
                            Name = "Tad",
                            Personality = "orange",
                            PreferredDiet = "[]",
                            SpeciesId = 1,
                            Weight = 178.57630819452459,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 24,
                            EnclosureId = 17,
                            Gender = 1,
                            Name = "Austin",
                            Personality = "turquoise",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 914.5610344240614,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 25,
                            EnclosureId = 8,
                            Gender = 0,
                            Name = "Dawson",
                            Personality = "azure",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 32.598700610561963,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 26,
                            EnclosureId = 23,
                            Gender = 1,
                            Name = "Eveline",
                            Personality = "turquoise",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 118.4380769244423,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 27,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Melissa",
                            Personality = "salmon",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 689.93358086890839,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 28,
                            EnclosureId = 16,
                            Gender = 0,
                            Name = "Carol",
                            Personality = "fuchsia",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 872.800996169825,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 29,
                            EnclosureId = 15,
                            Gender = 0,
                            Name = "Clifton",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 159.32035601740108,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 30,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Charles",
                            Personality = "silver",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 904.40822489346056,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 31,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Richard",
                            Personality = "teal",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 906.44707505750307,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 32,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Leda",
                            Personality = "orange",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 330.34316868532022,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 33,
                            EnclosureId = 23,
                            Gender = 1,
                            Name = "Coby",
                            Personality = "blue",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 661.54804445511286,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 34,
                            EnclosureId = 18,
                            Gender = 0,
                            Name = "Reyna",
                            Personality = "pink",
                            PreferredDiet = "[]",
                            SpeciesId = 6,
                            Weight = 741.81025880914126,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 35,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Eda",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 912.82588666268487,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 36,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Margarita",
                            Personality = "green",
                            PreferredDiet = "[]",
                            SpeciesId = 12,
                            Weight = 881.35571939039221,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 37,
                            EnclosureId = 18,
                            Gender = 0,
                            Name = "Dessie",
                            Personality = "green",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 97.013370914228233,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 38,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Frida",
                            Personality = "azure",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 21.319800763874536,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 39,
                            EnclosureId = 8,
                            Gender = 1,
                            Name = "Kellie",
                            Personality = "teal",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 397.22791687862474,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 40,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Bethany",
                            Personality = "white",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 209.05904033088777,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 41,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Marisol",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 519.81911011584396,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 42,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Rafael",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 37.893575953495706,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 43,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Susan",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 973.89274547991272,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 44,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Chelsie",
                            Personality = "mint green",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 203.03350248204271,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 45,
                            EnclosureId = 19,
                            Gender = 0,
                            Name = "Jedidiah",
                            Personality = "ivory",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 212.33614075108522,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 46,
                            EnclosureId = 14,
                            Gender = 0,
                            Name = "Kane",
                            Personality = "olive",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 640.33842850091321,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 47,
                            EnclosureId = 10,
                            Gender = 1,
                            Name = "Theresa",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 491.92162001147148,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 48,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Amira",
                            Personality = "yellow",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 573.93254925395831,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 49,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Johnathan",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 516.22294430773968,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 50,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Ken",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 860.80651536707467,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 51,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Jacky",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 662.4528541227254,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 52,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Arvid",
                            Personality = "turquoise",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 932.06808232144488,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 53,
                            EnclosureId = 4,
                            Gender = 1,
                            Name = "Justus",
                            Personality = "teal",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 950.84875135421032,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 54,
                            EnclosureId = 4,
                            Gender = 1,
                            Name = "Alexandre",
                            Personality = "tan",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 922.91747972691394,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 55,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Maida",
                            Personality = "cyan",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 985.97829486397256,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 56,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Reta",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 814.01882319890956,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 57,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Viva",
                            Personality = "pink",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 947.42877459712781,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 58,
                            EnclosureId = 22,
                            Gender = 1,
                            Name = "Shania",
                            Personality = "mint green",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 574.96602688388862,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 59,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Cortez",
                            Personality = "teal",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 105.48258791956631,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 60,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Cordell",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 413.76282829905307,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 61,
                            EnclosureId = 19,
                            Gender = 0,
                            Name = "Keshaun",
                            Personality = "salmon",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 157.84982573720299,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 62,
                            EnclosureId = 17,
                            Gender = 1,
                            Name = "Kattie",
                            Personality = "purple",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 79.66670091422165,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 63,
                            EnclosureId = 21,
                            Gender = 1,
                            Name = "Emmitt",
                            Personality = "salmon",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 582.97771969103985,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 64,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Bryce",
                            Personality = "silver",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 753.83760336945784,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 65,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Imelda",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 498.34078580605285,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 66,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Winfield",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 164.13817728570575,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 67,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Sid",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 205.41193051004441,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 68,
                            EnclosureId = 13,
                            Gender = 0,
                            Name = "Maida",
                            Personality = "blue",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 929.46023679351163,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 69,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Tomas",
                            Personality = "fuchsia",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 206.58144470464285,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 70,
                            EnclosureId = 18,
                            Gender = 1,
                            Name = "Webster",
                            Personality = "white",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 825.73382781925329,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 71,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Merle",
                            Personality = "mint green",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 493.20008717245946,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 72,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Stacey",
                            Personality = "indigo",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 148.34480559729727,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 73,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Hillary",
                            Personality = "black",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 398.59457082432857,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 74,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Toni",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 665.34907555359678,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 75,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Deven",
                            Personality = "ivory",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 304.81422544759965,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 76,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Israel",
                            Personality = "lime",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 3.3033548844260845,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 77,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Yasmine",
                            Personality = "turquoise",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 217.09617293904688,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 78,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Fidel",
                            Personality = "lime",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 218.12858717296768,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 79,
                            EnclosureId = 14,
                            Gender = 0,
                            Name = "Chasity",
                            Personality = "lime",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 735.03878103586726,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 80,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Jaclyn",
                            Personality = "fuchsia",
                            PreferredDiet = "[]",
                            SpeciesId = 3,
                            Weight = 937.27304233087762,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 81,
                            EnclosureId = 8,
                            Gender = 0,
                            Name = "Litzy",
                            Personality = "orange",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 326.93058760531665,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 82,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Lucio",
                            Personality = "black",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 773.95838179394036,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 83,
                            EnclosureId = 22,
                            Gender = 0,
                            Name = "Elvis",
                            Personality = "olive",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 498.34972006918377,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 84,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Gia",
                            Personality = "indigo",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 136.94229419003386,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 85,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Libbie",
                            Personality = "cyan",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 403.35062788285427,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 86,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Casimir",
                            Personality = "black",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 417.23319766075912,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 87,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Kali",
                            Personality = "gold",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 573.16862454321779,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 88,
                            EnclosureId = 19,
                            Gender = 1,
                            Name = "Alysha",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 17,
                            Weight = 554.40272698872616,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 89,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Troy",
                            Personality = "purple",
                            PreferredDiet = "[]",
                            SpeciesId = 17,
                            Weight = 175.73308781684605,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 90,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Christina",
                            Personality = "cyan",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 240.2312437581291,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 91,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Clinton",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 288.84572522836345,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 92,
                            EnclosureId = 16,
                            Gender = 0,
                            Name = "Karlie",
                            Personality = "blue",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 517.2513146449603,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 93,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Lavern",
                            Personality = "maroon",
                            PreferredDiet = "[]",
                            SpeciesId = 11,
                            Weight = 927.97806030997731,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 94,
                            EnclosureId = 15,
                            Gender = 0,
                            Name = "Tia",
                            Personality = "tan",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 602.05155649595395,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sed accusamus cupiditate qui natus aspernatur debitis qui officia aut.",
                            Name = "similique",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dolor omnis eos consequatur nisi quisquam nihil dolore quisquam blanditiis.",
                            Name = "recusandae",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Qui ipsa dolores eum qui laudantium non porro maxime dicta.",
                            Name = "quia",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vero animi ut consectetur fugiat nihil distinctio cum labore cupiditate.",
                            Name = "explicabo",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sint modi mollitia tempora at iure sit temporibus illo id.",
                            Name = "et",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Exercitationem et ea dolore non et ad saepe sapiente quaerat.",
                            Name = "perspiciatis",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Minima illo illo quo et voluptatibus ea laboriosam provident laboriosam.",
                            Name = "possimus",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Nam necessitatibus inventore quae ut natus excepturi vero et vitae.",
                            Name = "excepturi",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Rerum cumque ad deleniti eligendi doloribus sed non quidem fugit.",
                            Name = "sed",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Corporis rerum ullam quia sunt iusto non exercitationem consequatur sint.",
                            Name = "laboriosam",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Impedit sapiente hic ut modi est vero eligendi eveniet voluptatem.",
                            Name = "facere",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Nesciunt id nam magni accusamus optio voluptatibus ratione omnis commodi.",
                            Name = "et",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Quo omnis dolorum assumenda ipsum magni architecto delectus consequatur ea.",
                            Name = "aut",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "A qui eius atque voluptas at natus perferendis porro aliquam.",
                            Name = "expedita",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Impedit sapiente sed molestiae sit dolores quis sapiente iusto velit.",
                            Name = "illo",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Dignissimos laborum dolorem adipisci hic enim minus dignissimos voluptatibus excepturi.",
                            Name = "pariatur",
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PredatorEnclosure")
                        .HasColumnType("bit");

                    b.Property<int>("PredatorSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorSpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 4,
                            Habitat = 32,
                            Name = "iusto",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 14,
                            SecurityRequired = 0,
                            Size = 164.04346789189742,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            Climate = 4,
                            Habitat = 16,
                            Name = "quis",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 8,
                            SecurityRequired = 0,
                            Size = 925.48451868484187,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Climate = 0,
                            Habitat = 8,
                            Name = "reiciendis",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 2,
                            SecurityRequired = 0,
                            Size = 724.94404095978632,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Climate = 3,
                            Habitat = 32,
                            Name = "minima",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 16,
                            SecurityRequired = 2,
                            Size = 949.29909397392964,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Climate = 3,
                            Habitat = 8,
                            Name = "laborum",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 3,
                            SecurityRequired = 2,
                            Size = 571.54021628702935,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            Climate = 3,
                            Habitat = 32,
                            Name = "magni",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 15,
                            SecurityRequired = 1,
                            Size = 992.60645128947749,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            Climate = 4,
                            Habitat = 16,
                            Name = "dignissimos",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 1,
                            SecurityRequired = 1,
                            Size = 619.46179924021214,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Climate = 3,
                            Habitat = 8,
                            Name = "ut",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 4,
                            SecurityRequired = 1,
                            Size = 820.72005837068957,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Climate = 1,
                            Habitat = 16,
                            Name = "sunt",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 11,
                            SecurityRequired = 0,
                            Size = 224.80451108390236,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Climate = 1,
                            Habitat = 32,
                            Name = "fuga",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 15,
                            SecurityRequired = 2,
                            Size = 248.37510521887702,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            Climate = 1,
                            Habitat = 8,
                            Name = "et",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 11,
                            SecurityRequired = 1,
                            Size = 185.01608535899356,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            Climate = 0,
                            Habitat = 32,
                            Name = "necessitatibus",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 6,
                            SecurityRequired = 1,
                            Size = 471.28694725658102,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            Climate = 0,
                            Habitat = 2,
                            Name = "illum",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 16,
                            SecurityRequired = 1,
                            Size = 152.87086977106222,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            Climate = 0,
                            Habitat = 64,
                            Name = "deserunt",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 17,
                            SecurityRequired = 0,
                            Size = 262.21969692400029,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            Climate = 1,
                            Habitat = 32,
                            Name = "ut",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 8,
                            SecurityRequired = 0,
                            Size = 467.80714565528393,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            Climate = 2,
                            Habitat = 8,
                            Name = "et",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 1,
                            SecurityRequired = 1,
                            Size = 227.8022432045978,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            Climate = 3,
                            Habitat = 16,
                            Name = "saepe",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 11,
                            SecurityRequired = 3,
                            Size = 384.7940124817149,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 18,
                            Climate = 3,
                            Habitat = 8,
                            Name = "dolor",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 5,
                            SecurityRequired = 2,
                            Size = 130.48307553709083,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            Climate = 4,
                            Habitat = 64,
                            Name = "deserunt",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 6,
                            SecurityRequired = 0,
                            Size = 539.55276666639736,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            Climate = 1,
                            Habitat = 32,
                            Name = "dolores",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 7,
                            SecurityRequired = 1,
                            Size = 284.97968513297053,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 21,
                            Climate = 4,
                            Habitat = 2,
                            Name = "praesentium",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 15,
                            SecurityRequired = 2,
                            Size = 243.87339475390567,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            Climate = 3,
                            Habitat = 4,
                            Name = "aut",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 17,
                            SecurityRequired = 0,
                            Size = 627.42766231742178,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            Climate = 1,
                            Habitat = 4,
                            Name = "tenetur",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 16,
                            SecurityRequired = 3,
                            Size = 586.40116632976321,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<int>("Diet")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Predator")
                        .HasColumnType("bit");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequired")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Hylobatidae spp.",
                            Name = "Koala",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 4,
                            SpaceRequired = 68.222552281930078
                        },
                        new
                        {
                            Id = 2,
                            Activity = 0,
                            Diet = 2,
                            LatinName = "Aptenodytes forsteri",
                            Name = "Sloth",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 3,
                            SpaceRequired = 33.242434547129974
                        },
                        new
                        {
                            Id = 3,
                            Activity = 2,
                            Diet = 2,
                            LatinName = "Mandrillus sphinx",
                            Name = "Golden Lion Tamarin",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 89.347231329436198
                        },
                        new
                        {
                            Id = 4,
                            Activity = 1,
                            Diet = 4,
                            LatinName = "Ara ararauna",
                            Name = "Black Rhinoceros",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 5,
                            SpaceRequired = 71.797261108894105
                        },
                        new
                        {
                            Id = 5,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Tremarctos ornatus",
                            Name = "White Rhinoceros",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 0,
                            SpaceRequired = 59.895704503207092
                        },
                        new
                        {
                            Id = 6,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Ailuropoda melanoleuca",
                            Name = "Spectacled Bear",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 1,
                            SpaceRequired = 26.447948249786776
                        },
                        new
                        {
                            Id = 7,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Ailurus fulgens",
                            Name = "American Alligator",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 4,
                            SpaceRequired = 97.582987921970556
                        },
                        new
                        {
                            Id = 8,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Ailuropoda melanoleuca",
                            Name = "African Wildcat",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 5,
                            SpaceRequired = 14.608120933596958
                        },
                        new
                        {
                            Id = 9,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Trichechus inunguis",
                            Name = "Goliath Frog",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 0,
                            SpaceRequired = 77.166847546186077
                        },
                        new
                        {
                            Id = 10,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Panthera uncia",
                            Name = "Red River Hog",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 1,
                            SpaceRequired = 11.091505302446109
                        },
                        new
                        {
                            Id = 11,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Gorilla beringei",
                            Name = "White-Tailed Deer",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 5,
                            SpaceRequired = 60.594695090837924
                        },
                        new
                        {
                            Id = 12,
                            Activity = 0,
                            Diet = 2,
                            LatinName = "Spheniscus humboldti",
                            Name = "Plains Zebra",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 61.874809154198225
                        },
                        new
                        {
                            Id = 13,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Cebus spp.",
                            Name = "Black Bear",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 0,
                            SpaceRequired = 77.485461372106798
                        },
                        new
                        {
                            Id = 14,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Acinonyx jubatus",
                            Name = "Red River Hog",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 4,
                            SpaceRequired = 44.803651369919223
                        },
                        new
                        {
                            Id = 15,
                            Activity = 0,
                            Diet = 1,
                            LatinName = "Varanus komodoensis",
                            Name = "Capuchin Monkey",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 5,
                            SpaceRequired = 16.193818496215471
                        },
                        new
                        {
                            Id = 16,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Gorilla gorilla gorilla",
                            Name = "Galapagos Tortoise",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 4,
                            SpaceRequired = 67.89606033791793
                        },
                        new
                        {
                            Id = 17,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Panthera tigris tigris",
                            Name = "Siamang",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 4,
                            SpaceRequired = 22.269711428472593
                        });
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZooModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Dandrechester",
                            Country = "Nicaragua",
                            Description = "Sit expedita iste est dolores.",
                            Name = "Gibson - Kub"
                        });
                });

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.HasOne("Zoo.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.HasOne("Zoo.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Categories")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.HasOne("Zoo.Models.Species", "PredatorSpecies")
                        .WithMany()
                        .HasForeignKey("PredatorSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredatorSpecies");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Categories");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
