// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Data;

#nullable disable

namespace Zoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20240701203024_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CategorySpecies");
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnclosureId = 13,
                            Gender = 1,
                            Name = "Mervin",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 955.54505064485227,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Cora",
                            Personality = "white",
                            PreferredDiet = "[]",
                            SpeciesId = 27,
                            Weight = 480.00988215321206,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            EnclosureId = 12,
                            Gender = 0,
                            Name = "Monte",
                            Personality = "ivory",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 91.113705747955208,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnclosureId = 3,
                            Gender = 1,
                            Name = "Pat",
                            Personality = "blue",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 578.52254452952502,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Merle",
                            Personality = "fuchsia",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 631.44611895164439,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Larry",
                            Personality = "green",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 64.719676901463089,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Maybelle",
                            Personality = "salmon",
                            PreferredDiet = "[]",
                            SpeciesId = 17,
                            Weight = 525.02640826957304,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            EnclosureId = 1,
                            Gender = 0,
                            Name = "Burley",
                            Personality = "cyan",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 158.43397249381636,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            EnclosureId = 8,
                            Gender = 1,
                            Name = "Carmella",
                            Personality = "mint green",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 89.027411784877671,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Dulce",
                            Personality = "green",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 703.11554906556967,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Sandrine",
                            Personality = "red",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 857.53398872551293,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Lisandro",
                            Personality = "indigo",
                            PreferredDiet = "[]",
                            SpeciesId = 16,
                            Weight = 908.57393160709364,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Olaf",
                            Personality = "pink",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 879.72204781784683,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Elyse",
                            Personality = "fuchsia",
                            PreferredDiet = "[]",
                            SpeciesId = 29,
                            Weight = 384.27217982337902,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Bridgette",
                            Personality = "gold",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 420.61897553075391,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            EnclosureId = 7,
                            Gender = 1,
                            Name = "Ruthie",
                            Personality = "white",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 749.95351886242088,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Josue",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 26,
                            Weight = 949.40907333048824,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 18,
                            EnclosureId = 11,
                            Gender = 0,
                            Name = "Lottie",
                            Personality = "lime",
                            PreferredDiet = "[]",
                            SpeciesId = 28,
                            Weight = 917.12067436684993,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Toney",
                            Personality = "yellow",
                            PreferredDiet = "[]",
                            SpeciesId = 21,
                            Weight = 830.58016108535628,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            EnclosureId = 12,
                            Gender = 1,
                            Name = "Josiane",
                            Personality = "purple",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 854.14785751548334,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 21,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Mac",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 25,
                            Weight = 410.68952251770423,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Rocio",
                            Personality = "gold",
                            PreferredDiet = "[]",
                            SpeciesId = 4,
                            Weight = 426.36068235352451,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 23,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Mia",
                            Personality = "blue",
                            PreferredDiet = "[]",
                            SpeciesId = 30,
                            Weight = 996.20374893821918,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 24,
                            EnclosureId = 16,
                            Gender = 0,
                            Name = "Jeffery",
                            Personality = "salmon",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 843.6994533211855,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 25,
                            EnclosureId = 4,
                            Gender = 1,
                            Name = "Adriel",
                            Personality = "indigo",
                            PreferredDiet = "[]",
                            SpeciesId = 29,
                            Weight = 898.30908373158638,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 26,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Dena",
                            Personality = "black",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 622.68374838021646,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 27,
                            EnclosureId = 16,
                            Gender = 1,
                            Name = "Quincy",
                            Personality = "yellow",
                            PreferredDiet = "[]",
                            SpeciesId = 26,
                            Weight = 976.41819942979191,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 28,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Shemar",
                            Personality = "yellow",
                            PreferredDiet = "[]",
                            SpeciesId = 30,
                            Weight = 488.75278707357546,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 29,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Wilmer",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 503.64438559214625,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 30,
                            EnclosureId = 16,
                            Gender = 0,
                            Name = "Garfield",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 28,
                            Weight = 231.76651583082935,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 31,
                            EnclosureId = 10,
                            Gender = 1,
                            Name = "Stanley",
                            Personality = "red",
                            PreferredDiet = "[]",
                            SpeciesId = 24,
                            Weight = 986.60228940433808,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 32,
                            EnclosureId = 15,
                            Gender = 0,
                            Name = "Henderson",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 9,
                            Weight = 651.17959579716421,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 33,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Skylar",
                            Personality = "violet",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 657.06034269710517,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 34,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Dorcas",
                            Personality = "olive",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 21.742941701340797,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 35,
                            EnclosureId = 13,
                            Gender = 0,
                            Name = "Johanna",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 29.236927379378976,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 36,
                            EnclosureId = 6,
                            Gender = 0,
                            Name = "Kobe",
                            Personality = "sky blue",
                            PreferredDiet = "[]",
                            SpeciesId = 8,
                            Weight = 498.85704938185125,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 37,
                            EnclosureId = 14,
                            Gender = 1,
                            Name = "Aletha",
                            Personality = "tan",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 970.29339243484503,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 38,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Alan",
                            Personality = "silver",
                            PreferredDiet = "[]",
                            SpeciesId = 2,
                            Weight = 380.48611130316249,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 39,
                            EnclosureId = 17,
                            Gender = 1,
                            Name = "Enos",
                            Personality = "fuchsia",
                            PreferredDiet = "[]",
                            SpeciesId = 15,
                            Weight = 260.35880567879281,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 40,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Lane",
                            Personality = "maroon",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 728.43166919067926,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 41,
                            EnclosureId = 11,
                            Gender = 1,
                            Name = "Amelie",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 13,
                            Weight = 266.63263485726975,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 42,
                            EnclosureId = 5,
                            Gender = 1,
                            Name = "Ward",
                            Personality = "lavender",
                            PreferredDiet = "[]",
                            SpeciesId = 27,
                            Weight = 695.03678419539222,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 43,
                            EnclosureId = 8,
                            Gender = 1,
                            Name = "Maryam",
                            Personality = "red",
                            PreferredDiet = "[]",
                            SpeciesId = 21,
                            Weight = 575.75497514103506,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 44,
                            EnclosureId = 4,
                            Gender = 0,
                            Name = "Herbert",
                            Personality = "green",
                            PreferredDiet = "[]",
                            SpeciesId = 20,
                            Weight = 382.07793669890214,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 45,
                            EnclosureId = 9,
                            Gender = 1,
                            Name = "Ben",
                            Personality = "plum",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 442.20946378554049,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 46,
                            EnclosureId = 17,
                            Gender = 1,
                            Name = "Jamal",
                            Personality = "indigo",
                            PreferredDiet = "[]",
                            SpeciesId = 5,
                            Weight = 454.24424561504708,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 47,
                            EnclosureId = 17,
                            Gender = 0,
                            Name = "Elinore",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 478.28693888688514,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 48,
                            EnclosureId = 2,
                            Gender = 0,
                            Name = "Kristopher",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 14,
                            Weight = 609.26578755106289,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 49,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Quinten",
                            Personality = "red",
                            PreferredDiet = "[]",
                            SpeciesId = 30,
                            Weight = 249.23161881433805,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 50,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Charlie",
                            Personality = "green",
                            PreferredDiet = "[]",
                            SpeciesId = 24,
                            Weight = 754.72475669120058,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 51,
                            EnclosureId = 1,
                            Gender = 1,
                            Name = "Twila",
                            Personality = "yellow",
                            PreferredDiet = "[]",
                            SpeciesId = 7,
                            Weight = 267.31887191937267,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 52,
                            EnclosureId = 15,
                            Gender = 0,
                            Name = "Alexandria",
                            Personality = "black",
                            PreferredDiet = "[]",
                            SpeciesId = 18,
                            Weight = 431.0097565913415,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 53,
                            EnclosureId = 15,
                            Gender = 1,
                            Name = "Armando",
                            Personality = "orchid",
                            PreferredDiet = "[]",
                            SpeciesId = 21,
                            Weight = 971.1452951322874,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 54,
                            EnclosureId = 6,
                            Gender = 1,
                            Name = "Ezequiel",
                            Personality = "ivory",
                            PreferredDiet = "[]",
                            SpeciesId = 10,
                            Weight = 925.72622650703931,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 55,
                            EnclosureId = 3,
                            Gender = 0,
                            Name = "Hollie",
                            Personality = "teal",
                            PreferredDiet = "[]",
                            SpeciesId = 27,
                            Weight = 566.03428483003108,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 56,
                            EnclosureId = 2,
                            Gender = 1,
                            Name = "Ivory",
                            Personality = "cyan",
                            PreferredDiet = "[]",
                            SpeciesId = 27,
                            Weight = 752.85831790149268,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 57,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Evelyn",
                            Personality = "salmon",
                            PreferredDiet = "[]",
                            SpeciesId = 22,
                            Weight = 135.10563433896377,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 58,
                            EnclosureId = 9,
                            Gender = 0,
                            Name = "Devan",
                            Personality = "tan",
                            PreferredDiet = "[]",
                            SpeciesId = 27,
                            Weight = 981.26312391598037,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 59,
                            EnclosureId = 7,
                            Gender = 0,
                            Name = "Omari",
                            Personality = "grey",
                            PreferredDiet = "[]",
                            SpeciesId = 23,
                            Weight = 10.76240532938086,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 60,
                            EnclosureId = 8,
                            Gender = 1,
                            Name = "Helene",
                            Personality = "azure",
                            PreferredDiet = "[]",
                            SpeciesId = 24,
                            Weight = 164.23825719010026,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 61,
                            EnclosureId = 5,
                            Gender = 0,
                            Name = "Jimmy",
                            Personality = "violet",
                            PreferredDiet = "[]",
                            SpeciesId = 26,
                            Weight = 970.92271271762195,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Car",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Shirt",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Towels",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Mouse",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Chicken",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Towels",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Table",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Table",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Mouse",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Cheese",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Chicken",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Salad",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tuna",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Fish",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Chips",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Chicken",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Chicken",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Bacon",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Salad",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ball",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 21,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Towels",
                            ZooId = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Pizza",
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PredatorEnclosure")
                        .HasColumnType("bit");

                    b.Property<int>("PredatorSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredatorSpeciesId");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 1,
                            Habitat = 1,
                            Name = "Hong Kong",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 8,
                            SecurityRequired = 0,
                            Size = 880.84451418594188,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            Climate = 3,
                            Habitat = 1,
                            Name = "Rwanda",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 14,
                            SecurityRequired = 0,
                            Size = 851.95175872785546,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Climate = 2,
                            Habitat = 8,
                            Name = "Namibia",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 19,
                            SecurityRequired = 0,
                            Size = 551.77531366630365,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Climate = 0,
                            Habitat = 32,
                            Name = "Cocos (Keeling) Islands",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 6,
                            SecurityRequired = 1,
                            Size = 601.52449542055956,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Climate = 0,
                            Habitat = 1,
                            Name = "Belarus",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 10,
                            SecurityRequired = 0,
                            Size = 440.7104040192587,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 6,
                            Climate = 2,
                            Habitat = 32,
                            Name = "Greece",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 24,
                            SecurityRequired = 3,
                            Size = 911.75524335095861,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 7,
                            Climate = 4,
                            Habitat = 16,
                            Name = "Mexico",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 8,
                            SecurityRequired = 3,
                            Size = 338.88923959313342,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 8,
                            Climate = 3,
                            Habitat = 32,
                            Name = "Andorra",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 29,
                            SecurityRequired = 2,
                            Size = 277.38865291864528,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 9,
                            Climate = 2,
                            Habitat = 16,
                            Name = "Austria",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 27,
                            SecurityRequired = 1,
                            Size = 682.27273426556872,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 10,
                            Climate = 3,
                            Habitat = 8,
                            Name = "Norway",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 10,
                            SecurityRequired = 0,
                            Size = 385.19431073536879,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 11,
                            Climate = 4,
                            Habitat = 2,
                            Name = "Mauritius",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 6,
                            SecurityRequired = 3,
                            Size = 424.33784803973771,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            Climate = 2,
                            Habitat = 4,
                            Name = "Palau",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 12,
                            SecurityRequired = 2,
                            Size = 225.16425291076726,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 13,
                            Climate = 0,
                            Habitat = 1,
                            Name = "Samoa",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 19,
                            SecurityRequired = 1,
                            Size = 637.08161665872785,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 14,
                            Climate = 4,
                            Habitat = 8,
                            Name = "Congo",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 14,
                            SecurityRequired = 0,
                            Size = 165.87353400557805,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 15,
                            Climate = 2,
                            Habitat = 1,
                            Name = "Republic of Korea",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 26,
                            SecurityRequired = 1,
                            Size = 222.11061809017065,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 16,
                            Climate = 1,
                            Habitat = 2,
                            Name = "Nepal",
                            PredatorEnclosure = false,
                            PredatorSpeciesId = 14,
                            SecurityRequired = 0,
                            Size = 911.40787776956802,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 17,
                            Climate = 4,
                            Habitat = 32,
                            Name = "Niue",
                            PredatorEnclosure = true,
                            PredatorSpeciesId = 4,
                            SecurityRequired = 3,
                            Size = 963.94093806019669,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<int>("Diet")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Predator")
                        .HasColumnType("bit");

                    b.Property<int>("SecurityRequired")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequired")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Giraffa camelopardalis",
                            Name = "Tiger",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 0,
                            SpaceRequired = 88.460708380369269
                        },
                        new
                        {
                            Id = 2,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Panthera tigris sumatrae",
                            Name = "African Penguin",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 1,
                            SpaceRequired = 87.633967744062232
                        },
                        new
                        {
                            Id = 3,
                            Activity = 2,
                            Diet = 3,
                            LatinName = "Trichechus spp.",
                            Name = "African Grey Parrot",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 2,
                            SpaceRequired = 65.884924687879305
                        },
                        new
                        {
                            Id = 4,
                            Activity = 1,
                            Diet = 4,
                            LatinName = "Bradypus spp.",
                            Name = "Red Kangaroo",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 0,
                            SpaceRequired = 27.096385922713264
                        },
                        new
                        {
                            Id = 5,
                            Activity = 2,
                            Diet = 4,
                            LatinName = "Ceratotherium simum",
                            Name = "Siamang",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 3,
                            SpaceRequired = 60.138309500837643
                        },
                        new
                        {
                            Id = 6,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Elephas maximus",
                            Name = "Puma",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 0,
                            SpaceRequired = 77.30513071854611
                        },
                        new
                        {
                            Id = 7,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Conraua goliath",
                            Name = "Golden Eagle",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 57.187642922638886
                        },
                        new
                        {
                            Id = 8,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Haliaeetus leucocephalus",
                            Name = "Gibbon",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 0,
                            SpaceRequired = 75.093834657924361
                        },
                        new
                        {
                            Id = 9,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Suricata suricatta",
                            Name = "Sumatran Tiger",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 5,
                            SpaceRequired = 72.995315086334159
                        },
                        new
                        {
                            Id = 10,
                            Activity = 0,
                            Diet = 2,
                            LatinName = "Ara ararauna",
                            Name = "Chimpanzee",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 4,
                            SpaceRequired = 99.270789916753372
                        },
                        new
                        {
                            Id = 11,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Panthera tigris",
                            Name = "Aldabra Giant Tortoise",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 1,
                            SpaceRequired = 89.053093533691836
                        },
                        new
                        {
                            Id = 12,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Nasua spp.",
                            Name = "Tiger",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 5,
                            SpaceRequired = 89.121976906538578
                        },
                        new
                        {
                            Id = 13,
                            Activity = 2,
                            Diet = 1,
                            LatinName = "Pongo pygmaeus",
                            Name = "Komodo Dragon",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 0,
                            SpaceRequired = 86.597154501647083
                        },
                        new
                        {
                            Id = 14,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Odocoileus virginianus",
                            Name = "Common Ostrich",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 5,
                            SpaceRequired = 49.004174810506285
                        },
                        new
                        {
                            Id = 15,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Giraffa camelopardalis",
                            Name = "White-Tailed Deer",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 0,
                            SpaceRequired = 98.109969737456282
                        },
                        new
                        {
                            Id = 16,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Phascolarctos cinereus",
                            Name = "Red Panda",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 3,
                            SpaceRequired = 85.129108459007341
                        },
                        new
                        {
                            Id = 17,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Ursus americanus",
                            Name = "Golden Eagle",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 90.206075040907137
                        },
                        new
                        {
                            Id = 18,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Alligator mississippiensis",
                            Name = "American Alligator",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 4,
                            SpaceRequired = 31.340144746159641
                        },
                        new
                        {
                            Id = 19,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Pteronura brasiliensis",
                            Name = "American Alligator",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 2,
                            SpaceRequired = 10.553757273863893
                        },
                        new
                        {
                            Id = 20,
                            Activity = 2,
                            Diet = 0,
                            LatinName = "Spheniscus humboldti",
                            Name = "Spectacled Bear",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 1,
                            SpaceRequired = 81.441223424869179
                        },
                        new
                        {
                            Id = 21,
                            Activity = 1,
                            Diet = 1,
                            LatinName = "Spheniscus demersus",
                            Name = "Plains Zebra",
                            Predator = true,
                            SecurityRequired = 1,
                            Size = 3,
                            SpaceRequired = 18.303023966727061
                        },
                        new
                        {
                            Id = 22,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Ursus americanus",
                            Name = "Bengal Tiger",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 2,
                            SpaceRequired = 50.366014695894521
                        },
                        new
                        {
                            Id = 23,
                            Activity = 2,
                            Diet = 3,
                            LatinName = "Giraffa camelopardalis",
                            Name = "Emperor Penguin",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 5,
                            SpaceRequired = 45.851097544766752
                        },
                        new
                        {
                            Id = 24,
                            Activity = 1,
                            Diet = 4,
                            LatinName = "Panthera tigris",
                            Name = "Siberian Tiger",
                            Predator = true,
                            SecurityRequired = 2,
                            Size = 3,
                            SpaceRequired = 19.714078602875276
                        },
                        new
                        {
                            Id = 25,
                            Activity = 1,
                            Diet = 4,
                            LatinName = "Pongo spp.",
                            Name = "Lion",
                            Predator = true,
                            SecurityRequired = 3,
                            Size = 1,
                            SpaceRequired = 11.241002845247055
                        },
                        new
                        {
                            Id = 26,
                            Activity = 1,
                            Diet = 3,
                            LatinName = "Vulpes zerda",
                            Name = "Red Panda",
                            Predator = false,
                            SecurityRequired = 0,
                            Size = 3,
                            SpaceRequired = 81.068368168582438
                        },
                        new
                        {
                            Id = 27,
                            Activity = 0,
                            Diet = 3,
                            LatinName = "Giraffa camelopardalis",
                            Name = "African Wild Dog",
                            Predator = false,
                            SecurityRequired = 2,
                            Size = 3,
                            SpaceRequired = 10.583627483738752
                        },
                        new
                        {
                            Id = 28,
                            Activity = 1,
                            Diet = 2,
                            LatinName = "Pteronura brasiliensis",
                            Name = "Bengal Tiger",
                            Predator = true,
                            SecurityRequired = 0,
                            Size = 0,
                            SpaceRequired = 98.851422389896513
                        },
                        new
                        {
                            Id = 29,
                            Activity = 1,
                            Diet = 0,
                            LatinName = "Panthera onca",
                            Name = "Mandrill",
                            Predator = false,
                            SecurityRequired = 3,
                            Size = 0,
                            SpaceRequired = 96.212415005781082
                        },
                        new
                        {
                            Id = 30,
                            Activity = 0,
                            Diet = 0,
                            LatinName = "Giraffa camelopardalis",
                            Name = "Gharial",
                            Predator = false,
                            SecurityRequired = 1,
                            Size = 4,
                            SpaceRequired = 88.208860940973352
                        });
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZooModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "D'angeloport",
                            Country = "Congo",
                            Description = "one of my hobbies is scuba diving. and when i'm scuba diving this works great.",
                            Name = "Cartwright - Hammes"
                        });
                });

            modelBuilder.Entity("CategorySpecies", b =>
                {
                    b.HasOne("Zoo.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.HasOne("Zoo.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.Models.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Category", b =>
                {
                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Categories")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.HasOne("Zoo.Models.Species", "PredatorSpecies")
                        .WithMany()
                        .HasForeignKey("PredatorSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.Models.ZooModel", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredatorSpecies");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Zoo.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.Models.ZooModel", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Categories");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
