apiVersion: v1
kind: Config
clusters:
  - name: microk8s-cluster
    cluster:
      certificate-authority-data: {{ca_data}}
      server: https://{{cluster_url}}:16443
contexts:
  - name: group{{group_number}}-context
    context:
      cluster: microk8s-cluster
      namespace: group{{group_number}}
      user: group{{group_number}}-user
current-context: group{{group_number}}-context
users:
  - name: group{{group_number}}-user
    user:
      token: {{token}}