name: Unit Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # Change to your desired .NET version
        
    - name: Restore dependencies
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build

  upload-test-results:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: ${{ github.workspace }}/test-results
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: ${{ github.workspace }}/test-results
